# 此設定檔用要放在 ~/.config/kh-volume/config.yaml
# 若沒有此檔案，程式會使用內建的預設值
settings:
  # 虛擬輸出裝置名稱
  sink_name: kh150_sink
  sink_desc: KH150\ Controller

  # 是否啟用音訊流自動轉接功能 (True/False)
  enable_redirect: True

  # 真正用來播放聲音的硬體輸出裝置名稱
  real_sink_name: alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink

  # khtool 相關設定
  khtool_repo: ~/Codespace/khtool/khtool.py
  khtool_workdir: ~/.local/state/kh-volume
  iface: enp0s13f0u2u4u2

  # 音量範圍對應 (0 - 120 dB)
  db_min: 40
  db_max: 90

  # 初始狀態
  init_vol_pct: 20
  init_mute: False